### ISSUE TITLE
Fork ? alternative ?

### ISSUE THREAD

**Issue by bflorat** [thombergs/docx-stamper#101]
This project seems abandoned by it original author still 2019.

I still thank him for his great piece of code and as an open source project admin myself, I understand very well that this he ows nothing to us.

However, it is paramount for some of my professional projects and I choosed it when very active back in 2018. I suppose I'm not the only one in this case.

Does somebody know an alternative ? think about a serious fork ?

**Comment by bflorat** [comment]
@crgardner  No but I didn't actively searched. 

Note that I had to fork this project to fix #32. I [forked this project](https://github.com/bflorat/docx-stamper) to fix this. It is available on Maven central at
``` 
  <dependency>
            <groupId>net.florat</groupId>
            <artifactId>docx-stamper</artifactId>
            <version>1.4.0~1</version>
        </dependency>
```

Let me know if you find an alternative.

**Comment by dallanmc** [comment]
I got rid of all that index stuff in the codebase. You can just delete the object by getting the parent and then calling remove on it and pass in the object you want to remove. It greatly simplified the codebase.

**Comment by bflorat** [comment]
Thanks. I don't remember well but it must be more or less what I did [here](https://github.com/thombergs/docx-stamper/pull/46/commits/5b299c5a27b9a402a86b592e1c02efa096c67cff)

I also restored the maven packaging, I don't use gradle.

**Comment by crgardner** [comment]
My understanding is that newer java 11 docx4j rely on the jee jarkata
packages but stamper expects javax objects. I was wanting to see if stamper
could be updated to use the newer docx4j versions and hence be able to deal
either Jakarta packages.

**Comment by josephverron** [comment]
I'm interested in an active fork as well, we are getting more and more invested in this piece of code at my workplace.
If any of you want to start and maintain an open source fork, we could participate.

**Comment by bflorat** [comment]
I'd like to but I for one have absolutely not the time to do it seriously. 

Let us know if you start a fork, I may send MR.

**Comment by josephverron** [comment]
We are starting to actively fork the repo
You can find it here : https://github.com/verronpro/docx-stamper.
We started find improving the  repeatDocPart, and making it recursive, and learning the way to publish to maven central. Thanks for the inspiration!

**Comment by dallanmc** [comment]
This is great - I have a good few improvements that I have implemented (they are in the issues section) - but maybe you've implemented some of them already. A couple of useful ones would be the `displayWordIf` processor and the `displaySectionIf` processor. 
I also implemented the concept of preprocessors. I was facing an issue where spelling errors in the document would mess up the processing, so one preprocessor I made would remove all the spelling errors from the xml doc before then processing properly. 
I also implemented a `replaceWordsWith` for commenting around multiple words which works well.

I am sure there is other stuff, but it's probably in the issues section too.

**Comment by bflorat** [comment]
This is great !  I'll re-send you this PR https://github.com/thombergs/docx-stamper/pull/46 ASAP to fix the most important issue I have with this project.

**Comment by josephverron** [comment]
> This is great - I have a good few improvements that I have implemented (they are in the issues section) - but maybe you've implemented some of them already. A couple of useful ones would be the `displayWordIf` processor and the `displaySectionIf` processor. I also implemented the concept of preprocessors. I was facing an issue where spelling errors in the document would mess up the processing, so one preprocessor I made would remove all the spelling errors from the xml doc before then processing properly. I also implemented a `replaceWordsWith` for commenting around multiple words which works well.
> 
> I am sure there is other stuff, but it's probably in the issues section too.

Thanks @dallanmc, you can make the merge requests yourself on https://github.com/verronpro/docx-stamper with maybe a test case, and i'll include them. If not, then i might take them on myself during the coming month.

**Comment by bflorat** [comment]
Good work everybody !  Does the `repeatDocPart()` feature actually works now ? (even when elements are removed). 

If it works now, I may try it again.

**Comment by josephverron** [comment]
I did not try concurrently with the remove feature, but the repeatDocPart works and use only the given object as sub-context for the "doc part" covered by the comment.
