### ISSUE TITLE
Add support for $root / $parent special variable inside repeat context

### ISSUE THREAD

**Issue by t-oster** [thombergs/docx-stamper#104]
When I am inside repeatTableRow or repeatDocPart, is there a way I can access properties from the parent/root context? In knockout js, they provide the special variables $parent/$root.
If there is no such mechanism yet, I could maybe implement it.

**Comment by t-oster** [comment]
The Spring EL also has a #root object https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/expressions.html, but it does not seem to point at the root evaluation context during a repeatDocPart

**Comment by dallanmc** [comment]
Not an ideal solution, but you could use comments to resolve the variable (assuming your pointing at a single variable and not a repeating one).

**Comment by t-oster** [comment]
Nevermind. I resolved it by manually registering the variable **#parent**:
```java
DocxStamper stamper = new DocxStamperConfiguration()
            .setEvaluationContextConfigurer(ctx -> ctx.setVariable("parent", context))
        .build();
```

this way I can use the variable "#parent" everywhere. I tried "root", but that seems to be reserved somehow. As long as DocXStamper does not support nested repeats, root and parent are always the same, so I can live with that.

**Comment by t-oster** [comment]
... of cause one could add this as a feature and also add **#index**, **#first** and **#last** variables for the iterations, but that's another story.
