### ISSUE TITLE
Use comments to replace text

### ISSUE THREAD

**Issue by crivera** [thombergs/docx-stamper#13]
Hi

i was wondering if its possible to use comments to replace certain text parts.

so instead of writing:

Hello ${client.firstName} ${client.lastName}

i would like to see if i could write

Hello Tom Harry and add comments on the parts that should be replaced.

Some of the data fields can be long which messes up formatting.

Thanks for the great library
Chris

**Comment by crivera** [comment]
oh and the comment would be over Tom and say something like: ${client.firstName}

**Comment by crivera** [comment]
Not sure if you care but I did find a solution myself and created a fork which has the fix

https://github.com/crivera/docx-stamper

Let me know what you think and if you care to have it merged

Thanks again for the great library

Chris

**Comment by thombergs** [comment]
Of course I care :).

Thanks for the idea and your solution.

I've taken a look at your solution. It will have problems in some cases, for example when you have the same text twice in a paragraph and only the second has a replacement comment. In this case the first match will be replaced. Also, the CommentWalker may have problems with overlapping comments.

The solution i would go for is implementing a CommentProcessor (see DisplayIfProcessor for example) which provides a new method "replaceWith(String replacement)" to be used in comments. All Runs within the comment are then replaced with a single Run that has the content of the replacement parameter (similar to what you implemented, but only replacing the Runs that are really within that comment).

I would implement this solution myself some time, but cannot promise a date. If you would like to implement this idea, feel free to drop a pull request or any questions you might have. If you'd like me to review something, just drop a comment.

Regards,
Tom

**Comment by crivera** [comment]
cool ill give it a try :)

**Comment by crivera** [comment]
hi tom

i finally had some more time to look at this and i think i came up with a pretty good solution. I am using your same mechanics that you already have and just extended on them.

i also updated some dependencies to their latest version and wrote a unit test for the new example.

the only thing i think that still can be improved is the Coordinates Walker

i added a new walkParagraph which now checks through each run in a paragraph and calls the onRun method. 

the main issue i found was that when i found the comment and replaced it i could not right away delete it because the for loop was still going on. so i had to pass back the comment and delete them all after the loop was complete... maybe you have an idea for that.

let me know if you like it or if you think some changes are still needed

Thanks
Chris

**Comment by thombergs** [comment]
Hi,

From the commits in your docx-stamper fork I cannot really see what you changed, since they include ALL files (see https://github.com/crivera/docx-stamper/commit/272afb6a2c0ffd788266ffb3eeea342a4d2b9d76). Can you please isolate your changes and commit them into a clean fork of docx-stamper (delete your old fork and create a new one)? When you are at it, you can even simply click the "Create Pull Request" Button after adding your changes. That way, I can easily review your changes and even directly merge them into this repository.

**Comment by crivera** [comment]
hey sorry for the bad commit... i am not super proficient in git yet :) 

i created a pull request. if you let me know when formatter you use (for eclipse) i can avoid that formatting issue on 1 or 2 files too

Chris
