### ISSUE TITLE
Add ability to repeat random text, not only tables

### ISSUE THREAD

**Issue by asm0dey** [thombergs/docx-stamper#15]
We have a case when several paragraphs should be repeated several times (depending on model). Now it possible only with tables. It would be perfect to have ability to annotate them somehow

**Comment by thombergs** [comment]
Sounds like a sensible feature. I will have a look at it next weekend. Should not be too hard to implement.

**Comment by asm0dey** [comment]
Hello! Any news on this?

**Comment by thombergs** [comment]
Not yet, sorry. Haven't found the time yet. If you want to try yourself, have a look at the RepeatProcessor class. Essentially, you only have to add a new method `repeatParagraph` which does the same for paragraphs as `repeatTableRow` does for table rows.

**Comment by asm0dey** [comment]
I think problem is more complex, because I need to repeat group of paragraphs.

**Comment by thombergs** [comment]
That is indeed harder to implement since you have to find out which paragraphs are enclosed in the comment and then repeat all paragraphs. That would mean changing a lot of the internal classes, which I am currently not able to do.

**Comment by asm0dey** [comment]
Sorry to hear that. How do you think, will it be possible to emulate this kind of behaviour with repeating 1×1 invisible table with those paragraphs inside?

**Comment by wpcfree** [comment]
Is there any progress in this problem? I need it too!

**Comment by asm0dey** [comment]
@wpcfree As a workaround, we used 1×1 table with invisible border and text inside it.

**Comment by bk001** [comment]
This is a feature I would appreciate as well. 

An alternative approach might be a feature that supports including other word doc templates with a specific context (maybe this is already possible using Spring Expression Language?). If that was combined with a way of repeating the include, the included doc could contain anything.

**Comment by rlamarche** [comment]
Hi, I did a processor that allow repeating paragraphs and it works.
I'll fork the projet and add the custom processor.

**Comment by rlamarche** [comment]
Here the PR : https://github.com/thombergs/docx-stamper/pull/39
