### ISSUE TITLE
Provide an option to mark and replace line breaks

### ISSUE THREAD

**Issue by thombergs** [thombergs/docx-stamper#16]
Provide an option that allows to define a placeholder that is replaced by line breaks during stamping.

**Comment by thombergs** [comment]
You can now provide a lineBreakPlaceholder. See https://github.com/thombergs/docx-stamper/blob/master/src/test/java/org/wickedsource/docxstamper/LineBreakReplacementTest.java.

**Comment by Manerial** [comment]
Hello,

Is there a way to use paragraph break instead of line break ? I didn't find anything about this.

Thanks a lot,
Manerial
