### ISSUE TITLE
Allow to use custom property accessor

### ISSUE THREAD

**Issue by msiegenthaler** [thombergs/docx-stamper#27]
I need to use a custom spring PropertyAccessor. Basically it is because I'm using Scala.

Currently there is no way I know of to inject that into the ExpressionResolver. Basically I need to add the following
`    evaluationContext.addPropertyAccessor(new ScalaMapPropertyAccessor)`

Would you consider making it overwritable?

My proposed way to do so:

- add an extension method to ExpressionResolver. Like for example `void extendEvalutationContext(EvaluationContext ctx)` and call it inside resolveExpression
- add a way to provide a different ExpressionResolver to PlaceholderReplacer and CommentReplacer

PS: this is a really great library, thank you so much for writing it

**Comment by thombergs** [comment]
Sounds legit :). I would welcome a pull request with your proposed changes.

I would do it like this:
* create an interface `EvaluationContextExtender` (feel free to find a better name)
* add a method `extendEvaluationContextWith(EvaluationContextExtender extender)` to `DocxStamperConfiguation`
* pass this object to the ExpressionResolver where it will be called

**Comment by msiegenthaler** [comment]
Sure, I gave it a try at #28

**Comment by thombergs** [comment]
I just release 1.1.0 it should be available in Maven central soon.
