### ISSUE TITLE
Library Support to iterate the list and generate the doc content in the document

### ISSUE THREAD

**Issue by satishjs2297** [thombergs/docx-stamper#29]
Do we have any utility/api  support to iterate the list and generate the doc content in the document.

For instance: 
List<Address> addresses = new ArrayList<>();
Assume, addresses.size() is 4, then 4 times Address Info should be updated in the document with list address values. 

addresses.size() is 2, then 2 times Address Info should be updated in the document with list address values.

**Comment by thombergs** [comment]
Currently, repeating objects only works on table rows. See `repeatTableRow()` in the Readme of this project and [this word document](https://github.com/thombergs/docx-stamper/blob/master/src/test/resources/org/wickedsource/docxstamper/RepeatTableRowTest.docx) from the unit tests.

A feature for repeating other things than table rows is already requested in https://github.com/thombergs/docx-stamper/issues/15.
