### ISSUE TITLE
formatting is lost when expressions are replaced

### ISSUE THREAD

**Issue by thombergs** [thombergs/docx-stamper#3]
when an expression is replaced with the value it evaluates to, the formatting (e.g. "bold") gets lost.

**Comment by thombergs** [comment]
The PlaceholderReplacer (or rather the ParagraphWrapper that is called) neither preserves the rPr-property of the P (paragraph) nor the rPr-property of the R (runs). It should be possible to sopy the rPr property from the original into the newly generated paragraphs and runs.

**Comment by vexmenon** [comment]
Hi,
I am currently still facing an issue with the text losing is format. The bold format is changed to normal text.

**Comment by rishisc** [comment]
@thombergs any luck with formatting issue
