### ISSUE TITLE
Trouble implementing displayTableIf

### ISSUE THREAD

**Issue by asaladino** [thombergs/docx-stamper#35]
Hello.

Would you be able to provide directions for using displayTableIf. I have tried selecting text in a table cell or all the text in the table cell, then right clicking and creating a new comment that contains:

```displayTableIf(linksFoundCount > 0)```

but the table will always be visible. A commit with

```displayParagraphIf(linksFoundCount > 10)```

works really well for paragraphs. I think I'm just missing something small.
Thanks for your assistance.

**Comment by thombergs** [comment]
It should work exactly as you described. Perhaps take the following docx file as a basis and try to build on it: 

https://github.com/thombergs/docx-stamper/blob/master/src/test/resources/org/wickedsource/docxstamper/ConditionalDisplayOfTablesTest.docx

Also, in your `displayTableIf` example you compare against `0` while you compare against `10` in your `displayParagraphIf` example - is that intentional?

**Comment by asaladino** [comment]
Tom, thanks for the quick rely. I'm working from a corporate template, which may have seen a lot of miles. Today I'll start over with the suggested document and let you know.

Some other factors that might be causing the issue are:
- I'm using a mac to make edits to the docx in word, perhaps I should try libreoffice for the edits.
- I'm using kotlin for development not java.

Nice library, the best one I have tried 👏.

**Comment by asaladino** [comment]
Also, the comparison against `10` is intentional. If there are more than 10 links I would like to show a paragraph describing where they can get all the links. Would that affect the table display? It should be a valid conditional in SpEL.

**Comment by asaladino** [comment]
When I start from a blank document, everything works perfect. I'll have to add formatting later, after everything is populating. Thanks for your help.

**Comment by thombergs** [comment]
Glad that it works.

There may be some formatting quirks the office tools add after some time that docxstamper does not understand. If you can provide a document that did not work, I might find out what's wrong and teach docxstamper to handle it.

**Comment by asaladino** [comment]
Probably not necessary. I just stamped the file and Word notified me that the produced file is corrupt. So definitely a bad template.
<img width="541" alt="word-popup" src="https://user-images.githubusercontent.com/1087585/35301804-8fac70e6-005a-11e8-880b-8c1b163248f0.png">
