### ISSUE TITLE
templates saved using Word on Mac result in a corrupted doc

### ISSUE THREAD

**Issue by bk001** [thombergs/docx-stamper#36]
When I create or edit a template using MS Word for Mac (v16.9) opening the resulting 'stamped' doc results in an error:
![image](https://user-images.githubusercontent.com/35811357/35401199-c080e46c-01f0-11e8-9bab-5c3064d67b7d.png)

A seemingly identical template created using the online version results in a file without the error.

Attached is the template created using MS Word for Mac and the resulting 'stamped' output file containing the error.
[test-template.docx](https://github.com/thombergs/docx-stamper/files/1664878/test-template.docx)

[test-output.docx](https://github.com/thombergs/docx-stamper/files/1664879/test-output.docx)

Any suggestions appreciated.

Thanks

Ben

**Comment by acetous** [comment]
I get the same error message when saving my Word document using Microsoft Word 2016.

**Comment by acetous** [comment]
Updating docx4j to the current version 3.3.6 solved my issues.

Using Gradle: `compile('org.docx4j:docx4j:3.3.6')`

**Comment by bk001** [comment]
Thanks! That sorted it.
