### ISSUE TITLE
Publish 1.3.0 on mvn central

### ISSUE THREAD

**Issue by f-aubert** [thombergs/docx-stamper#47]
Would you consider publishing the latest version 1.3.0 on man central? Our entreprise is (unfortunately) very strict in which repositories it allow for our maven build, would you mind publishing on maven central?
Thanks again a lot for your amazing work.

**Comment by thombergs** [comment]
Hi Frederic,

it should be synced to Maven Central within a day or so. Get back to me if
it's not available in a couple days.

Regards,
Tom

Am So., 12. Aug. 2018 um 11:58 Uhr schrieb f-aubert <
notifications@github.com>:

**Comment by mateofacu** [comment]
Hi Tom , 
     I want to use this library in my project. It looks pretty awesome. 
     I'm trying to get version 1.3.0 but it is not published on bintray nor on mavencentral.
thanks, Facundo

**Comment by f-aubert** [comment]
It is! Thank you...

**Comment by mateofacu** [comment]
May be documentation is not up to date? I manually checked jcenter repository (from main page documentation)  and last version present is 1.2.2

**Comment by thombergs** [comment]
The namespace has changed (by accident). The group name is now `org.wickedsource.docx-stamper` instead of `org.wickedsource`.

See https://search.maven.org/search?q=g:org.wickedsource.docx-stamper.

I updated the docs.
