### ISSUE TITLE
Adding repeating functionality for a part in docx

### ISSUE THREAD

**Issue by ImanGharib** [thombergs/docx-stamper#50]
I am using the fantastic docx-stamper and it works really nice. I am facing a challenge using a dynamic layout. I mean a layout which has some repeating parts in it. ( a combination of paragraphs and tables which are to be repeated and filled with different values)
for example:
In part number ${partId} somthing...
**new page**
table 1-1
new page
table 2-1
**new page** 
In part number ${partId} somthing...
**new page**
table 1-2
**new page** 
table 2-2

and this can be repeated more times. 
Is it possible to develop functionality in docx-stamper which supports repeating parts? Something like repeatingParagraph() but can contain a section containing paragraphs and tables. In the example above I could have used this method and mark my first part (text and table 1) and they get a list which contains two elements for example and these have the value for each iteration.

**Comment by DDtKey** [comment]
I had a need for a similar functionality and I implemented this.
Perhaps in the future it will be able to replace any other existing repeat* functions.
The other day I will do PR.

**Comment by DDtKey** [comment]
Along the way, I found and fixed several bugs (related to comments) in the library, which I later fully describe in the PR.

Me need to fix a couple more things for full functionality and add a test.  
But I think it will be soon :)

**Comment by thombergs** [comment]
PR #78 has been merged and will be released with 1.4.0 soon
