### ISSUE TITLE
Compatability with Word for Mac and Office 365?

### ISSUE THREAD

**Issue by rthomason** [thombergs/docx-stamper#87]
I'm trying to create a template containing a simple table with multiple rows, similar to the RepeatTableRowTest test and couldn't get it working. In my local tests whenever I assert on rowCoords.size() it's always 2, since no rows are added.

So I tried manually creating the same document (RepeatTableRowTest.docx) in both Word for Mac v16.42 and in Office 365 and saving the file locally, and the test fails when either of those documents are used. Do I have to create the documents in Windows for this library to work?

Here is the document created in Word for Mac:
[RepeatTableRowTest.docx](https://github.com/thombergs/docx-stamper/files/5513469/RepeatTableRowTest.docx)

**Comment by DDtKey** [comment]
I also opened your document on a Mac and I don't see a comment 🤔 
After that I added a comment in accordance with the `docx-stamper` documentation (see screenshot) - and everything worked correctly.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/26835520/100230670-0d6ebd00-2f37-11eb-97b1-b1af2bbf2e4e.png">

I am attaching a corrected file (everything was also done on a Mac):
[RepeatTableRowTest.docx](https://github.com/thombergs/docx-stamper/files/5596797/RepeatTableRowTest.docx)

That is, it should work, besides, I used a `docx-stamper with templates made in the `LibreOffice` and everything was fine, the document creation programs have a rather small effect on this template engine 🙂

**Comment by rthomason** [comment]
Ok thanks. First time using the library and I didn't understand I needed to add a comment to create a dynamic table. I still don't see how they are related though, is that just the most efficient way to lookup the text in order to replace it?

**Comment by DDtKey** [comment]
This method is chosen by the author of the library.
I think this is a pretty convenient way, since we explicitly select (_right in the editor_) the area that needs to be repeated and which collection of objects to use.
